### PR TITLE
Create datapackage.json file

### PR DESCRIPTION
**Pull request by Ebnalblad**

### CODE REVIEW

**Comment by rgrp** [comment]
@Ebnalblad looks good and merging. One small thought: it might be nice to have description of some of the columns in the CSV - http://data.okfn.org/tools/view?url=https://github.com/okfn/licenses (e.g. osd_conformance might not be obvious what it means)

**Comment by rgrp** [comment]
@Ebnalblad did you think further about adding descriptions for any of the fields?

**Comment by Ebnalblad** [comment]
@rgrp sorry for late answer, next week I will have free time to check the file and add more clear descriptions

**Comment by Ebnalblad** [comment]
@rgrp I changed "od_conformance" to" conforming to the Open Definition" and  "osd_conformance" to "conforming to  Open Source Definition".
I also replaced " domain_content,domain_data,domain_software" with "open content , open data , open software". I believe that will make them more clear.

What is the meaning of "is_generic"  ? and what is the name do you suggest to make it more clear for people ?
Also for "maintainer" I think we can replace it with something more clear like "organization" , what do you think of that?

**Comment by rgrp** [comment]
is_generic was not specific to date or content i think.

Note these descriptions go in datapackage.json - if you are not clear just shout!

**Comment by Ebnalblad** [comment]
Sorry for the mistake , what about now? what are the changes i need to make ?

**Comment by rgrp** [comment]
see http://dataprotocols.org/json-table-schema/#field-descriptors - you want a description fields.

**Pull request merged**
