### PR TITLE
  Add some description to the columns names

### PR DESCRIPTION
**Pull request by Ebnalblad**

### CODE REVIEW

**Comment by rgrp** [comment]
@Ebnalblad can we get a new PR with just the datapackage.json changes - remember we do not want to change the column names on the csv.

**Comment by Ebnalblad** [comment]
i tried, but i could not make new PR. But the changes pushed, i deleted the changes in CSV file

**Comment by rgrp** [comment]
@Ebnalblad to be clear the change in datapackage.json is not hte change in field names but adding a "description" field with the description of the column. See http://dataprotocols.org/json-table-schema/#field-descriptors

**Comment by rgrp** [comment]
@Ebnalblad

**Comment by rgrp** [comment]
@Ebnalblad the thing would be to refork from current head - so you have clean CSV and then apply changes to datapackage.json

**Comment by Ebnalblad** [comment]
@rgrp i did it

**Pull request closed without merging**
