### PR TITLE
Fix recently updated license ids, port deploy script to python3, update generated csv

### PR DESCRIPTION
**Pull request by mlinksva**

### CODE REVIEW

**Comment by rufuspollock** [comment]
Wow, thanks @mlinksva this is awesome 🎉🙏 👏👏

**Review by rufuspollock — APPROVED** [review]
reviewed and all looks good! 👍

**Comment by adriens** [comment]
i'm having a look :rocket:

**Comment by adriens** [comment]
Now, everything looks perfect :rocket: 

<pre>D <font color="#8AE234"><b>select </b></font>* <font color="#8AE234"><b>from </b></font>
&gt; read_csv_auto(<font color="#C4A000">&apos;https://raw.githubusercontent.com/okfn/licenses/master/licenses.csv&apos;</font>)
&gt; <font color="#8AE234"><b>where</b></font>
&gt;     id <font color="#8AE234"><b>like </b></font><font color="#C4A000">&apos;CC-BY-ND%&apos; </font><font color="#8AE234"><b>or</b></font>
&gt;     id <font color="#8AE234"><b>like </b></font><font color="#C4A000">&apos;CC-BY-NC%&apos;</font>;
┌─────────────────┬────────────────┬─────────────┬─────────────────┬──────────────────┬────────────┬──────────────────┬────────────────┬─────────────────┬─────────┬──────────────────────┬─────────────────────────────────────┬────────────┐
│       id        │ domain_content │ domain_data │ domain_software │      family      │ is_generic │    maintainer    │ od_conformance │ osd_conformance │ status  │        title         │                 url                 │ legacy_ids │
│     varchar     │    boolean     │   boolean   │     boolean     │     varchar      │  boolean   │     varchar      │    varchar     │     varchar     │ varchar │       varchar        │               varchar               │  varchar   │
├─────────────────┼────────────────┼─────────────┼─────────────────┼──────────────────┼────────────┼──────────────────┼────────────────┼─────────────────┼─────────┼──────────────────────┼─────────────────────────────────────┼────────────┤
│ CC-BY-ND-4.0    │ true           │ true        │ false           │                  │            │ Creative Commons │ rejected       │ not reviewed    │ active  │ Attribution-NoDeri…  │ https://creativecommons.org/licen…  │            │
│ CC-BY-NC-4.0    │ true           │ true        │ false           │ Creative Commons │            │ Creative Commons │ rejected       │ not reviewed    │ active  │ Creative Commons A…  │ https://creativecommons.org/licen…  │            │
│ CC-BY-NC-ND-4.0 │ true           │ true        │ false           │                  │            │ Creative Commons │ rejected       │ not reviewed    │ active  │ Attribution-NonCom…  │ https://creativecommons.org/licen…  │            │
│ CC-BY-NC-SA-4.0 │ true           │ true        │ false           │                  │            │ Creative Commons │ rejected       │ not reviewed    │ active  │ Attribution-NonCom…  │ https://creativecommons.org/licen…  │            │
└───</pre>

**Comment by adriens** [comment]
:ok_hand:

**Pull request merged**
